# Generated by Django 3.0.5 on 2020-05-01 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructor', '0002_add_category_to_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=8), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_case', to='constructor.Product')),
                ('cooler', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=5), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_cooler', to='constructor.Product')),
                ('cpu', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=1), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_cpu', to='constructor.Product')),
                ('dvd', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=7), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_dvd', to='constructor.Product')),
                ('hdd', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=6), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_hdd', to='constructor.Product')),
                ('motherboard', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=2), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_motherboard', to='constructor.Product')),
                ('power', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=8), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_power', to='constructor.Product')),
                ('ram', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=4), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_ram', to='constructor.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_card', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_id=3), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_video_card', to='constructor.Product')),
            ],
        ),
    ]
