# Generated by Django 3.0.5 on 2020-05-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='case',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category_id', 8), ('name__contains', 'Корпус')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_case', to='constructor.Product'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='power',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category_id', 8), ('name__contains', 'Блок питания')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_power', to='constructor.Product'),
        ),
    ]
